/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ssp.infrastructure;

import software.amazon.awscdk.App;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.StackProps;

public class Deployment {

    public static void main(final String[] args) {
        App app = new App();

        AwsECRStack ecrCdkStack = new AwsECRStack(app, "ecr-stack");
        ApplicationStack testAppStack = new ApplicationStack(app, "test", ApplicationStackProps.builder()
                .ecrRepository(ecrCdkStack.getRepository())
                .build());
        ApplicationStack prodCdkStack = new ApplicationStack(app, "prod", ApplicationStackProps.builder()
                .ecrRepository(ecrCdkStack.getRepository())
                .build());
        PipelineStack pipelineStack = new PipelineStack(app, "pipeline-stack", PipelineStackProps.builder()
                .ecrRepository(ecrCdkStack.getRepository())
                .testFargateService(testAppStack.getFargateService())
                .prodFargateService(prodCdkStack.getFargateService())
                .greenTargetGroup(prodCdkStack.getGreenTargetGroup())
                .greenLoadBalancerListener(prodCdkStack.getGreenLoadBalancerListener())
                .build());

        app.synth();
    }
}
