/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ssp.infrastructure;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Deployment classUnderTest = new Deployment();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
